# -*- coding: utf-8 -*-
"""despliegue_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nU8xqbNyRJPbkrqh0IsYipmxiyu4NE1

# Despliegue

- Cargamos el modelo
- Cargamos los datos
- Preparamos los datos: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

import numpy as np
import pandas as pd

# Cargamos el modelo
import pickle
filename = 'modelo-clustering.pkl'
modelo, min_max_scaler, variables, centroides = pickle.load(open(filename, 'rb'))

# Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Segmentación de clientes (Clustering)')

st.header("Variables numéricas")
tenure = st.slider("Antigüedad (en meses)", min_value=0, max_value=72, step=1)
MonthlyCharges = st.slider("Pago Mensual", min_value=18.25, max_value=118.75, step=0.25)

st.header("Tipo de servicio de Internet")
InternetService = st.selectbox("Servicio de Internet", ["DSL", "Fiber optic", "No"])

st.header("Tipo de Contrato")
Contract = st.selectbox("Contrato", ["Month-to-month", "One year", "Two year"])

st.header("Método de Pago")
PaymentMethod = st.selectbox("Método de Pago", ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"])

st.header("Variables binarias")
SeniorCitizen    = st.selectbox("Adulto Mayor",             ["No", "Yes"])
Partner          = st.selectbox("Partner",                  ["No", "Yes"])
Dependents       = st.selectbox("Dependientes",             ["No", "Yes"])
OnlineSecurity   = st.selectbox("Seguridad Online",         ["No", "Yes"])
OnlineBackup     = st.selectbox("Respaldo Online",          ["No", "Yes"])
DeviceProtection = st.selectbox("Protección de Dispositivos", ["No", "Yes"])
TechSupport      = st.selectbox("Soporte Técnico",          ["No", "Yes"])
StreamingTV      = st.selectbox("Televisión",               ["No", "Yes"])
StreamingMovies  = st.selectbox("Plataformas Streaming",    ["No", "Yes"])
PaperlessBilling = st.selectbox("Factura Digital",          ["No", "Yes"])

# Dataframe
datos = [[tenure, MonthlyCharges, SeniorCitizen, Partner, InternetService, Contract,
          PaymentMethod, Dependents, OnlineSecurity, OnlineBackup, DeviceProtection,
          TechSupport, StreamingTV, StreamingMovies, PaperlessBilling]]
data = pd.DataFrame(datos, columns=['tenure', 'MonthlyCharges', 'SeniorCitizen', 'Partner', 'InternetService', 'Contract',
          'PaymentMethod', 'Dependents', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
          'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling'])

# Dummies
data = pd.get_dummies(data, columns=['InternetService', 'Contract', 'PaymentMethod'], drop_first=False, dtype=int)
data = pd.get_dummies(data, columns=['SeniorCitizen', 'Partner', 'Dependents', 'OnlineSecurity',
                                     'OnlineBackup', 'DeviceProtection', 'TechSupport',
                                     'StreamingTV', 'StreamingMovies', 'PaperlessBilling'],
                      drop_first=True, dtype=int)

# Alinear columnas
data = data.reindex(columns=variables, fill_value=0)

# Normalizar
data[['tenure', 'MonthlyCharges']] = min_max_scaler.transform(data[['tenure', 'MonthlyCharges']])

"""# **Predicción**"""

perfiles = {
    0: "Clientes nuevos con poca antigüedad de 15 meses, cargo mensual de 49 dólares, tienen DSL, contrato mes a mes, no tienen ningún servicio adicional, reciben factura digital.",
    1: "Clientes relativamente nuevos con antigüedad de 20 meses, cargo mensual de 86 dólares, usan fibra óptica, pagan por cheque electrónico, contrato mes a mes, no tienen ningún servicio adicional, reciben factura digital.",
    2: "Clientes con antigüedad media de 31 meses, cargo mensual bajo de alrededor de 21 dólares, sin servicio de internet ni servicios adicionales, contrato mes a mes, sin pareja ni dependientes, no reciben factura digital.",
    3: "Clientes con antigüedad alta de 57 meses, cargo mensual de 102 dólares, tienen fibra óptica, tienen pareja, tienen todos los servicios adicionales, reciben factura digital.",
    4: "Clientes con antigüedad alta de 51 meses, cargo mensual de 67 dólares, tienen DSL, contrato a dos años, tienen pareja, tienen todos los servicios adicionales, reciben factura digital."
}

# Botón y predicción
if st.button('Predecir'):
    cluster = modelo.predict(data)[0]
    st.subheader(f'Clúster asignado: {cluster}')
    st.write(perfiles[cluster])
    st.dataframe(centroides.iloc[[cluster]])
    st.warning("Modelo con silueta de 0.208")
